//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SolicitudReconocimientos.mx.gob.edomex.qasistemas2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CeroPapelWsPortBinding", Namespace="http://service.ceroPapel.dgsei.edomex.gob.mx/")]
    public partial class CeroPapelWs_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback firmarSolicitudOperationCompleted;
        
        private System.Threading.SendOrPostCallback reasignarSolicitudOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerDocumentoFirmadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback nuevaSolicitudOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerEvidenciaImprimibleOperationCompleted;
        
        private System.Threading.SendOrPostCallback existeSolicitudTerminadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerEvidenciaXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback nuevaSolicitudBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback nuevaSolicitudBatchSHA2OperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerEvidenciaXmlSHA2OperationCompleted;
        
        private System.Threading.SendOrPostCallback reenviarSolicitudOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelaSolicitudOperationCompleted;
        
        private System.Threading.SendOrPostCallback identificadorSolicitudOperationCompleted;
        
        private System.Threading.SendOrPostCallback solicitudValidadorIdentificadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback solicitudValidadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback solicitudValidadorSistemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerDocumentoOriginalOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerDocumentoFirmadoIdentificadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback identificadorSolicitudHashDocumentoFirmadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CeroPapelWs_Service() {
            this.Url = global::SolicitudReconocimientos.Properties.Settings.Default.SolicitudReconocimientos_mx_gob_edomex_qasistemas2_CeroPapelWs_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event firmarSolicitudCompletedEventHandler firmarSolicitudCompleted;
        
        /// <remarks/>
        public event reasignarSolicitudCompletedEventHandler reasignarSolicitudCompleted;
        
        /// <remarks/>
        public event obtenerDocumentoFirmadoCompletedEventHandler obtenerDocumentoFirmadoCompleted;
        
        /// <remarks/>
        public event nuevaSolicitudCompletedEventHandler nuevaSolicitudCompleted;
        
        /// <remarks/>
        public event obtenerEvidenciaImprimibleCompletedEventHandler obtenerEvidenciaImprimibleCompleted;
        
        /// <remarks/>
        public event existeSolicitudTerminadaCompletedEventHandler existeSolicitudTerminadaCompleted;
        
        /// <remarks/>
        public event obtenerEvidenciaXmlCompletedEventHandler obtenerEvidenciaXmlCompleted;
        
        /// <remarks/>
        public event nuevaSolicitudBatchCompletedEventHandler nuevaSolicitudBatchCompleted;
        
        /// <remarks/>
        public event nuevaSolicitudBatchSHA2CompletedEventHandler nuevaSolicitudBatchSHA2Completed;
        
        /// <remarks/>
        public event obtenerEvidenciaXmlSHA2CompletedEventHandler obtenerEvidenciaXmlSHA2Completed;
        
        /// <remarks/>
        public event reenviarSolicitudCompletedEventHandler reenviarSolicitudCompleted;
        
        /// <remarks/>
        public event cancelaSolicitudCompletedEventHandler cancelaSolicitudCompleted;
        
        /// <remarks/>
        public event identificadorSolicitudCompletedEventHandler identificadorSolicitudCompleted;
        
        /// <remarks/>
        public event solicitudValidadorIdentificadorCompletedEventHandler solicitudValidadorIdentificadorCompleted;
        
        /// <remarks/>
        public event solicitudValidadorCompletedEventHandler solicitudValidadorCompleted;
        
        /// <remarks/>
        public event solicitudValidadorSistemaCompletedEventHandler solicitudValidadorSistemaCompleted;
        
        /// <remarks/>
        public event obtenerDocumentoOriginalCompletedEventHandler obtenerDocumentoOriginalCompleted;
        
        /// <remarks/>
        public event obtenerDocumentoFirmadoIdentificadorCompletedEventHandler obtenerDocumentoFirmadoIdentificadorCompleted;
        
        /// <remarks/>
        public event identificadorSolicitudHashDocumentoFirmadoCompletedEventHandler identificadorSolicitudHashDocumentoFirmadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firmarSolicitud([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string firmanteCuts, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")] byte[] pkcs7) {
            object[] results = this.Invoke("firmarSolicitud", new object[] {
                        hashSolicitud,
                        firmanteCuts,
                        pkcs7});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void firmarSolicitudAsync(string hashSolicitud, string firmanteCuts, byte[] pkcs7) {
            this.firmarSolicitudAsync(hashSolicitud, firmanteCuts, pkcs7, null);
        }
        
        /// <remarks/>
        public void firmarSolicitudAsync(string hashSolicitud, string firmanteCuts, byte[] pkcs7, object userState) {
            if ((this.firmarSolicitudOperationCompleted == null)) {
                this.firmarSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfirmarSolicitudOperationCompleted);
            }
            this.InvokeAsync("firmarSolicitud", new object[] {
                        hashSolicitud,
                        firmanteCuts,
                        pkcs7}, this.firmarSolicitudOperationCompleted, userState);
        }
        
        private void OnfirmarSolicitudOperationCompleted(object arg) {
            if ((this.firmarSolicitudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.firmarSolicitudCompleted(this, new firmarSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void reasignarSolicitud([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string justificacion, [System.Xml.Serialization.XmlElementAttribute("listaFirmantes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] listaFirmantes, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool listaOrdenada) {
            this.Invoke("reasignarSolicitud", new object[] {
                        hashSolicitud,
                        justificacion,
                        listaFirmantes,
                        listaOrdenada});
        }
        
        /// <remarks/>
        public void reasignarSolicitudAsync(string hashSolicitud, string justificacion, string[] listaFirmantes, bool listaOrdenada) {
            this.reasignarSolicitudAsync(hashSolicitud, justificacion, listaFirmantes, listaOrdenada, null);
        }
        
        /// <remarks/>
        public void reasignarSolicitudAsync(string hashSolicitud, string justificacion, string[] listaFirmantes, bool listaOrdenada, object userState) {
            if ((this.reasignarSolicitudOperationCompleted == null)) {
                this.reasignarSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreasignarSolicitudOperationCompleted);
            }
            this.InvokeAsync("reasignarSolicitud", new object[] {
                        hashSolicitud,
                        justificacion,
                        listaFirmantes,
                        listaOrdenada}, this.reasignarSolicitudOperationCompleted, userState);
        }
        
        private void OnreasignarSolicitudOperationCompleted(object arg) {
            if ((this.reasignarSolicitudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reasignarSolicitudCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public documentoVO obtenerDocumentoFirmado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud) {
            object[] results = this.Invoke("obtenerDocumentoFirmado", new object[] {
                        hashSolicitud});
            return ((documentoVO)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerDocumentoFirmadoAsync(string hashSolicitud) {
            this.obtenerDocumentoFirmadoAsync(hashSolicitud, null);
        }
        
        /// <remarks/>
        public void obtenerDocumentoFirmadoAsync(string hashSolicitud, object userState) {
            if ((this.obtenerDocumentoFirmadoOperationCompleted == null)) {
                this.obtenerDocumentoFirmadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerDocumentoFirmadoOperationCompleted);
            }
            this.InvokeAsync("obtenerDocumentoFirmado", new object[] {
                        hashSolicitud}, this.obtenerDocumentoFirmadoOperationCompleted, userState);
        }
        
        private void OnobtenerDocumentoFirmadoOperationCompleted(object arg) {
            if ((this.obtenerDocumentoFirmadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerDocumentoFirmadoCompleted(this, new obtenerDocumentoFirmadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuevaSolicitud([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] solicitudVO solicitud) {
            object[] results = this.Invoke("nuevaSolicitud", new object[] {
                        solicitud});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nuevaSolicitudAsync(solicitudVO solicitud) {
            this.nuevaSolicitudAsync(solicitud, null);
        }
        
        /// <remarks/>
        public void nuevaSolicitudAsync(solicitudVO solicitud, object userState) {
            if ((this.nuevaSolicitudOperationCompleted == null)) {
                this.nuevaSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevaSolicitudOperationCompleted);
            }
            this.InvokeAsync("nuevaSolicitud", new object[] {
                        solicitud}, this.nuevaSolicitudOperationCompleted, userState);
        }
        
        private void OnnuevaSolicitudOperationCompleted(object arg) {
            if ((this.nuevaSolicitudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nuevaSolicitudCompleted(this, new nuevaSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public documentoVO obtenerEvidenciaImprimible([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud) {
            object[] results = this.Invoke("obtenerEvidenciaImprimible", new object[] {
                        hashSolicitud});
            return ((documentoVO)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerEvidenciaImprimibleAsync(string hashSolicitud) {
            this.obtenerEvidenciaImprimibleAsync(hashSolicitud, null);
        }
        
        /// <remarks/>
        public void obtenerEvidenciaImprimibleAsync(string hashSolicitud, object userState) {
            if ((this.obtenerEvidenciaImprimibleOperationCompleted == null)) {
                this.obtenerEvidenciaImprimibleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerEvidenciaImprimibleOperationCompleted);
            }
            this.InvokeAsync("obtenerEvidenciaImprimible", new object[] {
                        hashSolicitud}, this.obtenerEvidenciaImprimibleOperationCompleted, userState);
        }
        
        private void OnobtenerEvidenciaImprimibleOperationCompleted(object arg) {
            if ((this.obtenerEvidenciaImprimibleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerEvidenciaImprimibleCompleted(this, new obtenerEvidenciaImprimibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool existeSolicitudTerminada([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud) {
            object[] results = this.Invoke("existeSolicitudTerminada", new object[] {
                        hashSolicitud});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void existeSolicitudTerminadaAsync(string hashSolicitud) {
            this.existeSolicitudTerminadaAsync(hashSolicitud, null);
        }
        
        /// <remarks/>
        public void existeSolicitudTerminadaAsync(string hashSolicitud, object userState) {
            if ((this.existeSolicitudTerminadaOperationCompleted == null)) {
                this.existeSolicitudTerminadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexisteSolicitudTerminadaOperationCompleted);
            }
            this.InvokeAsync("existeSolicitudTerminada", new object[] {
                        hashSolicitud}, this.existeSolicitudTerminadaOperationCompleted, userState);
        }
        
        private void OnexisteSolicitudTerminadaOperationCompleted(object arg) {
            if ((this.existeSolicitudTerminadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.existeSolicitudTerminadaCompleted(this, new existeSolicitudTerminadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public documentoVO obtenerEvidenciaXml([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud) {
            object[] results = this.Invoke("obtenerEvidenciaXml", new object[] {
                        hashSolicitud});
            return ((documentoVO)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerEvidenciaXmlAsync(string hashSolicitud) {
            this.obtenerEvidenciaXmlAsync(hashSolicitud, null);
        }
        
        /// <remarks/>
        public void obtenerEvidenciaXmlAsync(string hashSolicitud, object userState) {
            if ((this.obtenerEvidenciaXmlOperationCompleted == null)) {
                this.obtenerEvidenciaXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerEvidenciaXmlOperationCompleted);
            }
            this.InvokeAsync("obtenerEvidenciaXml", new object[] {
                        hashSolicitud}, this.obtenerEvidenciaXmlOperationCompleted, userState);
        }
        
        private void OnobtenerEvidenciaXmlOperationCompleted(object arg) {
            if ((this.obtenerEvidenciaXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerEvidenciaXmlCompleted(this, new obtenerEvidenciaXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuevaSolicitudBatch([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] solicitudVO solicitud) {
            object[] results = this.Invoke("nuevaSolicitudBatch", new object[] {
                        solicitud});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nuevaSolicitudBatchAsync(solicitudVO solicitud) {
            this.nuevaSolicitudBatchAsync(solicitud, null);
        }
        
        /// <remarks/>
        public void nuevaSolicitudBatchAsync(solicitudVO solicitud, object userState) {
            if ((this.nuevaSolicitudBatchOperationCompleted == null)) {
                this.nuevaSolicitudBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevaSolicitudBatchOperationCompleted);
            }
            this.InvokeAsync("nuevaSolicitudBatch", new object[] {
                        solicitud}, this.nuevaSolicitudBatchOperationCompleted, userState);
        }
        
        private void OnnuevaSolicitudBatchOperationCompleted(object arg) {
            if ((this.nuevaSolicitudBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nuevaSolicitudBatchCompleted(this, new nuevaSolicitudBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuevaSolicitudBatchSHA2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] solicitudVO solicitud) {
            object[] results = this.Invoke("nuevaSolicitudBatchSHA2", new object[] {
                        solicitud});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nuevaSolicitudBatchSHA2Async(solicitudVO solicitud) {
            this.nuevaSolicitudBatchSHA2Async(solicitud, null);
        }
        
        /// <remarks/>
        public void nuevaSolicitudBatchSHA2Async(solicitudVO solicitud, object userState) {
            if ((this.nuevaSolicitudBatchSHA2OperationCompleted == null)) {
                this.nuevaSolicitudBatchSHA2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevaSolicitudBatchSHA2OperationCompleted);
            }
            this.InvokeAsync("nuevaSolicitudBatchSHA2", new object[] {
                        solicitud}, this.nuevaSolicitudBatchSHA2OperationCompleted, userState);
        }
        
        private void OnnuevaSolicitudBatchSHA2OperationCompleted(object arg) {
            if ((this.nuevaSolicitudBatchSHA2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nuevaSolicitudBatchSHA2Completed(this, new nuevaSolicitudBatchSHA2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public documentoVO obtenerEvidenciaXmlSHA2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud) {
            object[] results = this.Invoke("obtenerEvidenciaXmlSHA2", new object[] {
                        hashSolicitud});
            return ((documentoVO)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerEvidenciaXmlSHA2Async(string hashSolicitud) {
            this.obtenerEvidenciaXmlSHA2Async(hashSolicitud, null);
        }
        
        /// <remarks/>
        public void obtenerEvidenciaXmlSHA2Async(string hashSolicitud, object userState) {
            if ((this.obtenerEvidenciaXmlSHA2OperationCompleted == null)) {
                this.obtenerEvidenciaXmlSHA2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerEvidenciaXmlSHA2OperationCompleted);
            }
            this.InvokeAsync("obtenerEvidenciaXmlSHA2", new object[] {
                        hashSolicitud}, this.obtenerEvidenciaXmlSHA2OperationCompleted, userState);
        }
        
        private void OnobtenerEvidenciaXmlSHA2OperationCompleted(object arg) {
            if ((this.obtenerEvidenciaXmlSHA2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerEvidenciaXmlSHA2Completed(this, new obtenerEvidenciaXmlSHA2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void reenviarSolicitud([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string justificacion) {
            this.Invoke("reenviarSolicitud", new object[] {
                        hashSolicitud,
                        justificacion});
        }
        
        /// <remarks/>
        public void reenviarSolicitudAsync(string hashSolicitud, string justificacion) {
            this.reenviarSolicitudAsync(hashSolicitud, justificacion, null);
        }
        
        /// <remarks/>
        public void reenviarSolicitudAsync(string hashSolicitud, string justificacion, object userState) {
            if ((this.reenviarSolicitudOperationCompleted == null)) {
                this.reenviarSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreenviarSolicitudOperationCompleted);
            }
            this.InvokeAsync("reenviarSolicitud", new object[] {
                        hashSolicitud,
                        justificacion}, this.reenviarSolicitudOperationCompleted, userState);
        }
        
        private void OnreenviarSolicitudOperationCompleted(object arg) {
            if ((this.reenviarSolicitudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reenviarSolicitudCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void cancelaSolicitud([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string justificacion) {
            this.Invoke("cancelaSolicitud", new object[] {
                        hashSolicitud,
                        justificacion});
        }
        
        /// <remarks/>
        public void cancelaSolicitudAsync(string hashSolicitud, string justificacion) {
            this.cancelaSolicitudAsync(hashSolicitud, justificacion, null);
        }
        
        /// <remarks/>
        public void cancelaSolicitudAsync(string hashSolicitud, string justificacion, object userState) {
            if ((this.cancelaSolicitudOperationCompleted == null)) {
                this.cancelaSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelaSolicitudOperationCompleted);
            }
            this.InvokeAsync("cancelaSolicitud", new object[] {
                        hashSolicitud,
                        justificacion}, this.cancelaSolicitudOperationCompleted, userState);
        }
        
        private void OncancelaSolicitudOperationCompleted(object arg) {
            if ((this.cancelaSolicitudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelaSolicitudCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificadorSolicitud([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud) {
            object[] results = this.Invoke("identificadorSolicitud", new object[] {
                        hashSolicitud});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void identificadorSolicitudAsync(string hashSolicitud) {
            this.identificadorSolicitudAsync(hashSolicitud, null);
        }
        
        /// <remarks/>
        public void identificadorSolicitudAsync(string hashSolicitud, object userState) {
            if ((this.identificadorSolicitudOperationCompleted == null)) {
                this.identificadorSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnidentificadorSolicitudOperationCompleted);
            }
            this.InvokeAsync("identificadorSolicitud", new object[] {
                        hashSolicitud}, this.identificadorSolicitudOperationCompleted, userState);
        }
        
        private void OnidentificadorSolicitudOperationCompleted(object arg) {
            if ((this.identificadorSolicitudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.identificadorSolicitudCompleted(this, new identificadorSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public solicitudVO solicitudValidadorIdentificador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string identificador) {
            object[] results = this.Invoke("solicitudValidadorIdentificador", new object[] {
                        identificador});
            return ((solicitudVO)(results[0]));
        }
        
        /// <remarks/>
        public void solicitudValidadorIdentificadorAsync(string identificador) {
            this.solicitudValidadorIdentificadorAsync(identificador, null);
        }
        
        /// <remarks/>
        public void solicitudValidadorIdentificadorAsync(string identificador, object userState) {
            if ((this.solicitudValidadorIdentificadorOperationCompleted == null)) {
                this.solicitudValidadorIdentificadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsolicitudValidadorIdentificadorOperationCompleted);
            }
            this.InvokeAsync("solicitudValidadorIdentificador", new object[] {
                        identificador}, this.solicitudValidadorIdentificadorOperationCompleted, userState);
        }
        
        private void OnsolicitudValidadorIdentificadorOperationCompleted(object arg) {
            if ((this.solicitudValidadorIdentificadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.solicitudValidadorIdentificadorCompleted(this, new solicitudValidadorIdentificadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public solicitudVO solicitudValidador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string identificador, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cuts, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password) {
            object[] results = this.Invoke("solicitudValidador", new object[] {
                        identificador,
                        cuts,
                        password});
            return ((solicitudVO)(results[0]));
        }
        
        /// <remarks/>
        public void solicitudValidadorAsync(string identificador, string cuts, string password) {
            this.solicitudValidadorAsync(identificador, cuts, password, null);
        }
        
        /// <remarks/>
        public void solicitudValidadorAsync(string identificador, string cuts, string password, object userState) {
            if ((this.solicitudValidadorOperationCompleted == null)) {
                this.solicitudValidadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsolicitudValidadorOperationCompleted);
            }
            this.InvokeAsync("solicitudValidador", new object[] {
                        identificador,
                        cuts,
                        password}, this.solicitudValidadorOperationCompleted, userState);
        }
        
        private void OnsolicitudValidadorOperationCompleted(object arg) {
            if ((this.solicitudValidadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.solicitudValidadorCompleted(this, new solicitudValidadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public solicitudVO solicitudValidadorSistema([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string identificador) {
            object[] results = this.Invoke("solicitudValidadorSistema", new object[] {
                        identificador});
            return ((solicitudVO)(results[0]));
        }
        
        /// <remarks/>
        public void solicitudValidadorSistemaAsync(string identificador) {
            this.solicitudValidadorSistemaAsync(identificador, null);
        }
        
        /// <remarks/>
        public void solicitudValidadorSistemaAsync(string identificador, object userState) {
            if ((this.solicitudValidadorSistemaOperationCompleted == null)) {
                this.solicitudValidadorSistemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsolicitudValidadorSistemaOperationCompleted);
            }
            this.InvokeAsync("solicitudValidadorSistema", new object[] {
                        identificador}, this.solicitudValidadorSistemaOperationCompleted, userState);
        }
        
        private void OnsolicitudValidadorSistemaOperationCompleted(object arg) {
            if ((this.solicitudValidadorSistemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.solicitudValidadorSistemaCompleted(this, new solicitudValidadorSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public documentoVO obtenerDocumentoOriginal([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hashSolicitud) {
            object[] results = this.Invoke("obtenerDocumentoOriginal", new object[] {
                        hashSolicitud});
            return ((documentoVO)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerDocumentoOriginalAsync(string hashSolicitud) {
            this.obtenerDocumentoOriginalAsync(hashSolicitud, null);
        }
        
        /// <remarks/>
        public void obtenerDocumentoOriginalAsync(string hashSolicitud, object userState) {
            if ((this.obtenerDocumentoOriginalOperationCompleted == null)) {
                this.obtenerDocumentoOriginalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerDocumentoOriginalOperationCompleted);
            }
            this.InvokeAsync("obtenerDocumentoOriginal", new object[] {
                        hashSolicitud}, this.obtenerDocumentoOriginalOperationCompleted, userState);
        }
        
        private void OnobtenerDocumentoOriginalOperationCompleted(object arg) {
            if ((this.obtenerDocumentoOriginalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerDocumentoOriginalCompleted(this, new obtenerDocumentoOriginalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public documentoVO obtenerDocumentoFirmadoIdentificador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string identificador) {
            object[] results = this.Invoke("obtenerDocumentoFirmadoIdentificador", new object[] {
                        identificador});
            return ((documentoVO)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerDocumentoFirmadoIdentificadorAsync(string identificador) {
            this.obtenerDocumentoFirmadoIdentificadorAsync(identificador, null);
        }
        
        /// <remarks/>
        public void obtenerDocumentoFirmadoIdentificadorAsync(string identificador, object userState) {
            if ((this.obtenerDocumentoFirmadoIdentificadorOperationCompleted == null)) {
                this.obtenerDocumentoFirmadoIdentificadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerDocumentoFirmadoIdentificadorOperationCompleted);
            }
            this.InvokeAsync("obtenerDocumentoFirmadoIdentificador", new object[] {
                        identificador}, this.obtenerDocumentoFirmadoIdentificadorOperationCompleted, userState);
        }
        
        private void OnobtenerDocumentoFirmadoIdentificadorOperationCompleted(object arg) {
            if ((this.obtenerDocumentoFirmadoIdentificadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerDocumentoFirmadoIdentificadorCompleted(this, new obtenerDocumentoFirmadoIdentificadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", ResponseNamespace="http://service.ceroPapel.dgsei.edomex.gob.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificadorSolicitudHashDocumentoFirmado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hash) {
            object[] results = this.Invoke("identificadorSolicitudHashDocumentoFirmado", new object[] {
                        hash});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void identificadorSolicitudHashDocumentoFirmadoAsync(string hash) {
            this.identificadorSolicitudHashDocumentoFirmadoAsync(hash, null);
        }
        
        /// <remarks/>
        public void identificadorSolicitudHashDocumentoFirmadoAsync(string hash, object userState) {
            if ((this.identificadorSolicitudHashDocumentoFirmadoOperationCompleted == null)) {
                this.identificadorSolicitudHashDocumentoFirmadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnidentificadorSolicitudHashDocumentoFirmadoOperationCompleted);
            }
            this.InvokeAsync("identificadorSolicitudHashDocumentoFirmado", new object[] {
                        hash}, this.identificadorSolicitudHashDocumentoFirmadoOperationCompleted, userState);
        }
        
        private void OnidentificadorSolicitudHashDocumentoFirmadoOperationCompleted(object arg) {
            if ((this.identificadorSolicitudHashDocumentoFirmadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.identificadorSolicitudHashDocumentoFirmadoCompleted(this, new identificadorSolicitudHashDocumentoFirmadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ceroPapel.dgsei.edomex.gob.mx/")]
    public partial class documentoVO {
        
        private byte[] contenidoField;
        
        private string hashField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ceroPapel.dgsei.edomex.gob.mx/")]
    public partial class solicitudVO {
        
        private string asuntoField;
        
        private documentoVO documentoField;
        
        private System.DateTime fechaSolicitudField;
        
        private bool fechaSolicitudFieldSpecified;
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private string[] firmantesField;
        
        private string hashField;
        
        private string[][] listaFirmantesField;
        
        private bool listaOrdenadaField;
        
        private string sistemaSolicitanteField;
        
        private string solicitanteField;
        
        private int tipoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string asunto {
            get {
                return this.asuntoField;
            }
            set {
                this.asuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public documentoVO documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaSolicitud {
            get {
                return this.fechaSolicitudField;
            }
            set {
                this.fechaSolicitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSolicitudSpecified {
            get {
                return this.fechaSolicitudFieldSpecified;
            }
            set {
                this.fechaSolicitudFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("firmantes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] firmantes {
            get {
                return this.firmantesField;
            }
            set {
                this.firmantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[][] listaFirmantes {
            get {
                return this.listaFirmantesField;
            }
            set {
                this.listaFirmantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool listaOrdenada {
            get {
                return this.listaOrdenadaField;
            }
            set {
                this.listaOrdenadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sistemaSolicitante {
            get {
                return this.sistemaSolicitanteField;
            }
            set {
                this.sistemaSolicitanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string solicitante {
            get {
                return this.solicitanteField;
            }
            set {
                this.solicitanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void firmarSolicitudCompletedEventHandler(object sender, firmarSolicitudCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class firmarSolicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal firmarSolicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void reasignarSolicitudCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerDocumentoFirmadoCompletedEventHandler(object sender, obtenerDocumentoFirmadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerDocumentoFirmadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerDocumentoFirmadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentoVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentoVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void nuevaSolicitudCompletedEventHandler(object sender, nuevaSolicitudCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nuevaSolicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nuevaSolicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerEvidenciaImprimibleCompletedEventHandler(object sender, obtenerEvidenciaImprimibleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerEvidenciaImprimibleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerEvidenciaImprimibleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentoVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentoVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void existeSolicitudTerminadaCompletedEventHandler(object sender, existeSolicitudTerminadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class existeSolicitudTerminadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal existeSolicitudTerminadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerEvidenciaXmlCompletedEventHandler(object sender, obtenerEvidenciaXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerEvidenciaXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerEvidenciaXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentoVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentoVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void nuevaSolicitudBatchCompletedEventHandler(object sender, nuevaSolicitudBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nuevaSolicitudBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nuevaSolicitudBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void nuevaSolicitudBatchSHA2CompletedEventHandler(object sender, nuevaSolicitudBatchSHA2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nuevaSolicitudBatchSHA2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nuevaSolicitudBatchSHA2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerEvidenciaXmlSHA2CompletedEventHandler(object sender, obtenerEvidenciaXmlSHA2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerEvidenciaXmlSHA2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerEvidenciaXmlSHA2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentoVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentoVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void reenviarSolicitudCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cancelaSolicitudCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void identificadorSolicitudCompletedEventHandler(object sender, identificadorSolicitudCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class identificadorSolicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal identificadorSolicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void solicitudValidadorIdentificadorCompletedEventHandler(object sender, solicitudValidadorIdentificadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class solicitudValidadorIdentificadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal solicitudValidadorIdentificadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public solicitudVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((solicitudVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void solicitudValidadorCompletedEventHandler(object sender, solicitudValidadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class solicitudValidadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal solicitudValidadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public solicitudVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((solicitudVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void solicitudValidadorSistemaCompletedEventHandler(object sender, solicitudValidadorSistemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class solicitudValidadorSistemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal solicitudValidadorSistemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public solicitudVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((solicitudVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerDocumentoOriginalCompletedEventHandler(object sender, obtenerDocumentoOriginalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerDocumentoOriginalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerDocumentoOriginalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentoVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentoVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerDocumentoFirmadoIdentificadorCompletedEventHandler(object sender, obtenerDocumentoFirmadoIdentificadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerDocumentoFirmadoIdentificadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerDocumentoFirmadoIdentificadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentoVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentoVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void identificadorSolicitudHashDocumentoFirmadoCompletedEventHandler(object sender, identificadorSolicitudHashDocumentoFirmadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class identificadorSolicitudHashDocumentoFirmadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal identificadorSolicitudHashDocumentoFirmadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591